# GitHub PRの自動ラベル付け設定

# フロントエンド関連
frontend:
  - changed-files:
    - any-glob-to-any-file: 
      - 'app/**/*'
      - '**/*.tsx'
      - '**/*.css'
      - 'public/**/*'

# バックエンド関連
backend:
  - changed-files:
    - any-glob-to-any-file:
      - 'convex/**/*'
      - 'mastra-agents/**/*'

# 設定ファイル
config:
  - changed-files:
    - any-glob-to-any-file:
      - '*.json'
      - '*.js'
      - '*.mjs'
      - '*.config.*'
      - '.env*'
      - 'Makefile'

# CI/CD関連
ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'Makefile'

# ドキュメント
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'CLAUDE.md'
      - 'README.md'
      - '要件定義.md'

# TypeScript関連
typescript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.ts'
      - '**/*.tsx'
      - 'tsconfig.json'

# 依存関係
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'

# AI機能
ai:
  - changed-files:
    - any-glob-to-any-file:
      - 'convex/ai.ts'
      - '**/ai-*'
      - '**/*ai*'

# UI/UX
ui/ux:
  - changed-files:
    - any-glob-to-any-file:
      - '**/components/**/*'
      - '**/*.css'
      - 'tailwind.config.*'

# バグ修正
bugfix:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*fix*'