# GitHub PRの自動ラベル付け設定

# フロントエンド関連
frontend:
  - 'app/**/*'
  - '**/*.tsx'
  - '**/*.css'
  - 'public/**/*'

# バックエンド関連
backend:
  - 'convex/**/*'
  - 'mastra-agents/**/*'

# 設定ファイル
config:
  - '*.json'
  - '*.js'
  - '*.mjs'
  - '*.config.*'
  - '.env*'
  - 'Makefile'

# CI/CD関連
ci/cd:
  - '.github/**/*'
  - 'Makefile'

# ドキュメント
documentation:
  - '**/*.md'
  - 'CLAUDE.md'
  - 'README.md'
  - '要件定義.md'

# TypeScript関連
typescript:
  - '**/*.ts'
  - '**/*.tsx'
  - 'tsconfig.json'

# 依存関係
dependencies:
  - 'package.json'
  - 'package-lock.json'

# AI機能
ai:
  - 'convex/ai.ts'
  - '**/ai-*'
  - '**/*ai*'

# UI/UX
ui/ux:
  - '**/components/**/*'
  - '**/*.css'
  - 'tailwind.config.*'

# バグ修正 (ファイル名にfixが含まれる場合)
bugfix:
  - '**/*fix*'

# 機能追加 (featureブランチの場合)
feature:
  - any: ['feature/**/*']

# ホットフィックス
hotfix:
  - any: ['hotfix/**/*']